### ISSUE TITLE
Doesn't work from Azure Cloud Shell any more

### ISSUE THREAD

**Issue by p1johnson** [MicrosoftDocs/mslearn-monitor-diagnose-and-troubleshoot-azure-storage#4]
Following the "Monitor, diagnose and troubleshoot your Azure storage" on MS Learn. When running the code in Cloud Shell, it complains that it cannot find version 2.2.0 of .Net - Azure Cloud Shell has (at the time of writing this) version 3.1.9 installed.

**Comment by p1johnson** [comment]
Replacing `netcoreapp2.2` with `netcoreapp3.1` in StorageTest.csproj seems to allow it to run in Azure Cloud Shell (PowerShell) but that's the limit of my .NET skills.

**Comment by aimyresume** [comment]
Same for me, does not work.

**Comment by patridge** [comment]
Resolved via #7
